
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: mcm-git-demo-app
  namespace: mcm-git-demo-app
  generation: 1
  labels:
    app: mcm-git-demo-app
spec:
  componentKinds:
    - group: app.ibm.com
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - mcm-git-demo-app