apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: mcm-git-demo-app
  namespace: mcm-git-demo-app-channel
  generation: 1
  labels:
    app: mcm-git-demo-app
spec:
  template:
    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: mcm-git-demo-app
      namespace: default
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: mcm-git-demo-app
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: "30%"
          maxSurge: "90%"
      template:
        metadata:
          labels:
            app: mcm-git-demo-app
            version: current
        spec:
          containers:
          - name: mcm-git-demo-app
            image: niklaushirt/k8sdemo:1.0.0
            imagePullPolicy: Always 
            livenessProbe:
              httpGet:
                path: /
                port: 3000
              initialDelaySeconds: 10
              periodSeconds: 30
            readinessProbe:
              httpGet:
                path: /
                port: 3000
              initialDelaySeconds: 20
              periodSeconds: 10
            ports:
            - containerPort: 3000
            resources:
              requests:
                cpu: "50m"
                memory: "50Mi"
              limits:
                cpu: "50m"
                memory: "50Mi"
            env:
              - name: PORT
                value : "3000"
              - name: APPLICATION_NAME
                valueFrom:
                  configMapKeyRef:
                    name: mcm-git-demo-app-config
                    key: application-name
              - name: BACKEND_URL
                valueFrom:
                  configMapKeyRef:
                    name: mcm-git-demo-app-config
                    key: backend-url
